============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.3.3, pluggy-1.5.0
rootdir: /home/james/projects/cs6223/our_proptest_data
plugins: hypothesis-6.112.2, timeout-2.3.1
collected 10 items

mutants/statistics_variance/mutant_1.py .....                            [ 50%]
mutants/statistics_variance/mutant_2.py ..FF.                            [100%]

=================================== FAILURES ===================================
/home/james/projects/cs6223/our_proptest_data/mutants/statistics_variance/mutant_2.py:24: assert 0.3333333333333333 == 0
/home/james/projects/cs6223/our_proptest_data/mutants/statistics_variance/mutant_2.py:31: assert 2.0 == 0
=========================== short test summary info ============================
FAILED mutants/statistics_variance/mutant_2.py::test_violation_of_statistics_variance_3
FAILED mutants/statistics_variance/mutant_2.py::test_violation_of_statistics_variance_4
========================= 2 failed, 8 passed in 0.26s ==========================
