============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.3.3, pluggy-1.5.0
rootdir: /home/james/projects/cs6223/our_proptest_data
plugins: hypothesis-6.112.2, timeout-2.3.1
collected 20 items / 1 error

doc_and_code/proptest/datetime.datetime.fromisoformat/pbt_1.py FFF..     [ 25%]
doc_and_code/proptest/datetime.datetime.fromisoformat/pbt_3.py .....     [ 50%]
doc_and_code/proptest/datetime.datetime.fromisoformat/pbt_4.py ..F.F     [ 75%]
doc_and_code/proptest/datetime.datetime.fromisoformat/pbt_5.py FFF.F     [100%]

==================================== ERRORS ====================================
_ ERROR collecting doc_and_code/proptest/datetime.datetime.fromisoformat/pbt_2.py _
../../.venv/lib/python3.10/site-packages/_pytest/python.py:493: in importtestmodule
    mod = import_path(
../../.venv/lib/python3.10/site-packages/_pytest/pathlib.py:582: in import_path
    importlib.import_module(module_name)
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1050: in _gcd_import
    ???
<frozen importlib._bootstrap>:1027: in _find_and_load
    ???
<frozen importlib._bootstrap>:1006: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:688: in _load_unlocked
    ???
../../.venv/lib/python3.10/site-packages/_pytest/assertion/rewrite.py:175: in exec_module
    source_stat, co = _rewrite_test(fn, self.config)
../../.venv/lib/python3.10/site-packages/_pytest/assertion/rewrite.py:355: in _rewrite_test
    tree = ast.parse(source, filename=strfn)
/usr/lib/python3.10/ast.py:50: in parse
    return compile(source, filename, mode, flags,
E     File "/home/james/projects/cs6223/our_proptest_data/doc_and_code/proptest/datetime.datetime.fromisoformat/pbt_2.py", line 17
E       (f'+{d['tz_offset'][0]:02d}:{d['tz_offset'][1]:02d}' if d['tz_offset'][0] >= 0 else f'-{abs(d['tz_offset'][0]):02d}:{d['tz_offset'][1]:02d}')
E               ^^^^^^^^^
E   SyntaxError: f-string: f-string: unmatched '['
=================================== FAILURES ===================================
/home/james/projects/cs6223/our_proptest_data/doc_and_code/proptest/datetime.datetime.fromisoformat/pbt_1.py:23: ValueError: Invalid isoformat string: '0001-01-01T00:00:00.000000Z'
/home/james/projects/cs6223/our_proptest_data/doc_and_code/proptest/datetime.datetime.fromisoformat/pbt_1.py:34: ValueError: Invalid isoformat string: '0001-01-01T00:00:00.000000Z'
/home/james/projects/cs6223/our_proptest_data/doc_and_code/proptest/datetime.datetime.fromisoformat/pbt_1.py:44: ValueError: Invalid isoformat string: '0001-01-01T00:00:00.000000Z'
/home/james/projects/cs6223/our_proptest_data/doc_and_code/proptest/datetime.datetime.fromisoformat/pbt_4.py:65: exceptiongroup.ExceptionGroup: Hypothesis found 2 distinct failures. (2 sub-exceptions)
/home/james/projects/cs6223/our_proptest_data/doc_and_code/proptest/datetime.datetime.fromisoformat/pbt_4.py:97: exceptiongroup.ExceptionGroup: Hypothesis found 2 distinct failures. (2 sub-exceptions)
/home/james/projects/cs6223/our_proptest_data/doc_and_code/proptest/datetime.datetime.fromisoformat/pbt_5.py:7: ValueError: year 0 is out of range
/home/james/projects/cs6223/our_proptest_data/doc_and_code/proptest/datetime.datetime.fromisoformat/pbt_5.py:15: ValueError: year 0 is out of range
/home/james/projects/cs6223/our_proptest_data/doc_and_code/proptest/datetime.datetime.fromisoformat/pbt_5.py:27: ValueError: year 0 is out of range
/home/james/projects/cs6223/our_proptest_data/doc_and_code/proptest/datetime.datetime.fromisoformat/pbt_5.py:49: ValueError: year 0 is out of range
=========================== short test summary info ============================
FAILED doc_and_code/proptest/datetime.datetime.fromisoformat/pbt_1.py::test_datetime_datetime_fromisoformat_validity_property
FAILED doc_and_code/proptest/datetime.datetime.fromisoformat/pbt_1.py::test_datetime_datetime_fromisoformat_time_component_property
FAILED doc_and_code/proptest/datetime.datetime.fromisoformat/pbt_1.py::test_datetime_datetime_fromisoformat_timezone_property
FAILED doc_and_code/proptest/datetime.datetime.fromisoformat/pbt_4.py::test_timezone_handling_property
FAILED doc_and_code/proptest/datetime.datetime.fromisoformat/pbt_4.py::test_default_midnight_time_property
FAILED doc_and_code/proptest/datetime.datetime.fromisoformat/pbt_5.py::test_valid_date_components_property
FAILED doc_and_code/proptest/datetime.datetime.fromisoformat/pbt_5.py::test_correct_time_components_property
FAILED doc_and_code/proptest/datetime.datetime.fromisoformat/pbt_5.py::test_timezone_handling_property
FAILED doc_and_code/proptest/datetime.datetime.fromisoformat/pbt_5.py::test_default_midnight_property
ERROR doc_and_code/proptest/datetime.datetime.fromisoformat/pbt_2.py
==================== 9 failed, 11 passed, 1 error in 18.56s ====================
